-- 코드를 입력하세요
SELECT HISTORY_ID, CAR_ID, DATE_FORMAT(START_DATE, "%Y-%m-%d") START_DATE, DATE_FORMAT(END_DATE, "%Y-%m-%d") END_DATE, CASE
        WHEN MONTH(START_DATE) = 9 AND YEAR(START_DATE) = 2022 AND DATEDIFF(END_DATE, START_DATE) > 28 THEN '장기 대여'
        WHEN MONTH(START_DATE) = 9 AND YEAR(START_DATE) = 2022 AND DATEDIFF(END_DATE, START_DATE) <= 28 THEN '단기 대여'
        END AS RENT_TYPE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE MONTH(START_DATE) = 9 AND YEAR(START_DATE) = 2022
ORDER BY HISTORY_ID DESC