-- 코드를 작성해주세요
SELECT CASE WHEN DATE_FORMAT(DIFFERENTIATION_DATE, '%m%d') >= '1001' THEN '4Q'
            WHEN DATE_FORMAT(DIFFERENTIATION_DATE, '%m%d') >= '0701' THEN '3Q'
            WHEN DATE_FORMAT(DIFFERENTIATION_DATE, '%m%d') >= '0401' THEN '2Q'
        ELSE '1Q' END AS QUARTER, 
        COUNT(ID) AS ECOLI_COUNT
    FROM ECOLI_DATA
    GROUP BY
        CASE WHEN DATE_FORMAT(DIFFERENTIATION_DATE, '%m%d') >= '1001' THEN '4Q'
            WHEN DATE_FORMAT(DIFFERENTIATION_DATE, '%m%d') >= '0701' THEN '3Q'
            WHEN DATE_FORMAT(DIFFERENTIATION_DATE, '%m%d') >= '0401' THEN '2Q'
        ELSE '1Q' END
ORDER BY QUARTER ASC