-- 코드를 작성해주세요
SELECT YEAR(I.DIFFERENTIATION_DATE) YEAR, (T.SIZE - I.SIZE_OF_COLONY) AS YEAR_DEV, I.ID AS ID
    FROM (SELECT YEAR(DIFFERENTIATION_DATE) DIFYEAR, MAX(SIZE_OF_COLONY) AS SIZE
            FROM ECOLI_DATA
          GROUP BY YEAR(DIFFERENTIATION_DATE)) T JOIN ECOLI_DATA I ON T.DIFYEAR = YEAR(I.DIFFERENTIATION_DATE)
            ORDER BY YEAR, YEAR_DEV