-- 코드를 입력하세요
SELECT CATEGORY, SUM(S.SALES) TOTAL_SALES
    FROM BOOK B JOIN BOOK_SALES S
        ON B.BOOK_ID = S.BOOK_ID
    WHERE S.SALES_DATE >= '2022-01-01' AND S.SALES_DATE <= '2022-01-31'
    GROUP BY CATEGORY
ORDER BY CATEGORY