-- 코드를 작성해주세요
SELECT T.SCORE, T.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
    FROM (SELECT EMP_NO, SUM(SCORE) SCORE
            FROM HR_GRADE
         GROUP BY EMP_NO) T JOIN HR_EMPLOYEES E
         ON T.EMP_NO = E.EMP_NO
ORDER BY SCORE DESC
LIMIT 1