-- 코드를 작성해주세요
SELECT I.ID, N.FISH_NAME, I.LENGTH
    FROM (
        SELECT FISH_TYPE, MAX(LENGTH) LENGTH 
          FROM FISH_INFO GROUP BY FISH_TYPE
    ) T 
    JOIN FISH_INFO I ON T.LENGTH = I.LENGTH AND T.FISH_TYPE = I.FISH_TYPE
    JOIN FISH_NAME_INFO N ON I.FISH_TYPE = N.FISH_TYPE
ORDER BY I.ID